Fixed a data type error
Transaction Amount, Customer ID and Order ID may not be string and thus it returns the following error while performing a transaction: -
TypeError: params[key].includes is not a function.
I added an 'if' block outside beforw using ".includes" function and it resolved the issue.